------------------------------------------------------------------------------------------
-- company relation
------------------------------------------------------------------------------------------
/*
Consider the following relation company and answer questions 1 to 10.
- company (employee_id, name, position, start_date, salary, sector_id, sector_location)
*/

-- 1. Write an SQL query to find those employees who are either “Clerk” or “Analyst”. Sort the result set in descending order on position.

-- 2. Write an SQL query to find those employees whose names start with 'C' and five characters in length. Return employee name.

-- 3. Write an SQL query to find job positions having an average monthly salary of more than 2000.
     
-- 4. Write an SQL query to find those employees who started jobs before 2008. Return complete information about the employees.

-- 5. Write an SQL query to find those employees whose salary exceeds 3000 after giving a 30% increment.

-- 6. Write an SQL query to find all the employees whose annual salary is within the range of 20000 and 40000 (Begin and end values are included).

-- 7. Write an SQL query to count the number of employees of each designation in each sector. Return sector ID, position, and number of employees.

-- 8. Create a view named “employee_details” with the employee’s name, position and salary.

-- 9. Write an SQL query to count the number of characters for each employee's name. Return employee name length.

-- 10. Write an SQL query to find those employees who do not belong to sector 3004.

 ------------------------------------------------------------------------------------------
 -- Add seller, consumer, and products relations
 ------------------------------------------------------------------------------------------
/*
Consider the following relations and answer questions 11 to 20. Please use small letters in ascending order for aliasing tables when required.
- seller (seller_id, name, city)
- consumer (con_id, con_name, city, seller_id)
- products (order_no, amount, con_id, seller_id)
*/

-- 11. Write an SQL query to find those sellers who generated orders for their consumers but were not located in the same city.

-- 12. Write a SQL query to find the seller and consumer who belong to the same city.

-- 13. Write a SQL query to find the orders made by consumers. Return the order number and consumer name.

-- 14. Write a SQL statement to make a join on the tables seller, consumer and products in such a form that the same column of each table will appear once and only the relational rows will come.

-- 15. Write an SQL query to combine each row of the seller table with each row of the consumer table.

-- 16. Write a SQL query to find all the orders issued by the seller “Adam”.

-- 17. Write a SQL query to find all the orders, which are generated by those sellers, who live in the city of Manchester.

-- 18. Write a SQL query to find the seller whose place of living (city) matches with any of the cities where consumers live.

-- 19. Write a SQL query to find the seller who had more than one consumer. Return seller_id and name.

-- 20. Write an SQL query to find those orders, which are higher than the average amount of the orders.
